# Site settings
title: "Resume of Senior Technical Writer"
description: "A resume of Ivan Cheban, a senior technical writer."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Ivan Cheban"
resume_title:                   "Senior Technical Writer"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "ivancheban@gmail.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "+380952748078"
resume_contact_address:         "1/1 Dmytra Lutsenka Str., Kyiv"

resume_header_contact_info:     "Cell: +380952748078 • ivancheban@gmail.com"
display_header_contact_info:    "true"

resume_header_intro: "<ul>
  <li>4 years of experience as a technical writer</li>
  <li>10+ years of experience in translation and interpreting</li>
  <li>Experience in using MadCap Flare for writing technical documentation</li>
  <li>Confluence, Jira, Draw.io, Git</li>
  <li>Experience in writing about betting software, security systems, CMS, MDM systems</li>
  <li>Certified English translator</li>
</ul>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
# resume_section_projects:        true
resume_section_skills:          true
# resume_section_recognition:     true
# resume_section_links:           true
# resume_section_associations:    true
resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/ivancheban"
  # resume_twitter_url:           "http://twitter.com/jglovier"
  # resume_dribbble_url:          "https://dribbble.com/jag"
  resume_facebook_url:          "https://www.facebook.com/ivan.cheban.1"
  resume_linkedin_url:          "https://www.linkedin.com/in/ivan-cheban-a24b576"
  # resume_instagram_url:         "insert your Instagram URL here"
  resume_website_url:           "https://techwriter.netlify.app"
  # resume_medium_url:            "https://medium.com/@jglovier"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
